// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3eF59jP2ea53s0RqE8w5vE0r9lBrbUc0',
    appId: '1:935471196970:web:962767d538337202f4cc53',
    messagingSenderId: '935471196970',
    projectId: 'doctor-app-36ac4',
    authDomain: 'doctor-app-36ac4.firebaseapp.com',
    storageBucket: 'doctor-app-36ac4.firebasestorage.app',
    measurementId: 'G-BKGJMJ7ZRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHEJcjV0FaYRHPl4FN1A7GWk4hRtbQp80',
    appId: '1:935471196970:android:a2a099794901c11ff4cc53',
    messagingSenderId: '935471196970',
    projectId: 'doctor-app-36ac4',
    storageBucket: 'doctor-app-36ac4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-HOWaogJP4cLGyv6Z60tlKZNU6WecBLM',
    appId: '1:935471196970:ios:c2a19fee60064477f4cc53',
    messagingSenderId: '935471196970',
    projectId: 'doctor-app-36ac4',
    storageBucket: 'doctor-app-36ac4.firebasestorage.app',
    iosBundleId: 'com.example.respilinkApp',
  );
}
