import 'package:respilink_mobile/exports.dart';

class AppFormField extends TextFormField {
  AppFormField({
    super.key,
    required TextEditingController controller,
    String? label,
    String? hint,
    FormFieldValidator<String>? validator,
    TextInputType? keyboardType,
    bool obscureText = false,
    Widget? suffixIcon,
    Widget? prefixIcon,
    int? maxLines,
    int? maxLength,
    bool readOnly = false,
    VoidCallback? onTap,
    ValueChanged<String>? onFieldSubmitted,
  }) : super(
         controller: controller,
         maxLines: maxLines ?? 1,
         maxLength: maxLength,
         keyboardType: keyboardType ?? TextInputType.text,
         obscureText: obscureText,
         readOnly: readOnly,
         onFieldSubmitted: onFieldSubmitted,
         decoration: InputDecoration(
           labelText: label,
           counterText: "",
           hintText: hint,
           contentPadding: EdgeInsets.symmetric(vertical: 12.h, horizontal: 0),
           hintStyle: TextStyle(
             fontSize: 14.sp,
             color: AppColors.black.withValues(alpha: 0.4),
             fontFamily: AppConstants.fontFamily,
           ),
           labelStyle: TextStyle(
             fontSize: 14.sp,
             color: AppColors.primary,
             fontFamily: AppConstants.fontFamily,
           ),
           suffixIcon: suffixIcon,
           prefixIcon: prefixIcon,
           prefixIconConstraints: const BoxConstraints(
             minWidth: 30,
             minHeight: 0,
           ),
           border: UnderlineInputBorder(
             borderSide: BorderSide(color: AppColors.primary),
           ),
           focusedBorder: UnderlineInputBorder(
             borderSide: BorderSide(color: AppColors.primary),
           ),
           
         ),
         cursorColor: AppColors.primary,
         validator: validator,
         onTap: onTap,
         style: TextStyle(
           fontSize: 14.sp,
           color: AppColors.black,
           fontFamily: AppConstants.fontFamily,
         ),
       );

  AppFormField.filled({
    super.key,
    required TextEditingController controller,
    String? label,
    String? hint,
    FormFieldValidator<String>? validator,
    TextInputType? keyboardType,
    bool obscureText = false,
    Widget? suffixIcon,
    Widget? prefixIcon,
    int? maxLines,
    int? maxLength,
    bool readOnly = false,
    VoidCallback? onTap,
    ValueChanged<String>? onFieldSubmitted,
    Color? backgroundColor,
    ValueChanged<String?>? onChanged,
    bool? enabled,
    TextInputAction? inputAction,
    FocusNode? focusNode,
    Widget Function(BuildContext, EditableTextState)? contextMenuBuilder,
  }) : super(
         controller: controller,
         focusNode: focusNode,
         textInputAction: inputAction,
         maxLines: maxLines ?? 1,
         maxLength: maxLength,
         keyboardType: keyboardType ?? TextInputType.text,
         obscureText: obscureText,
         readOnly: readOnly,
         onFieldSubmitted: onFieldSubmitted,
         onChanged: onChanged,
         enabled: enabled ?? true,
         decoration: InputDecoration(
           labelText: label,
           hintText: hint,
           filled: true,
           counterText: "",
           fillColor: backgroundColor ?? AppColors.fieldColor,
           contentPadding: EdgeInsets.only(
             top: 12.h,
             bottom: 12.h,
             right: 2.w,
             left: 2.w,
           ),
           hintStyle: TextStyle(
             fontSize: 14.sp,
             color: AppColors.black.withValues(alpha: 0.4),
             fontFamily: AppConstants.fontFamily,
           ),
           labelStyle: TextStyle(
             fontSize: 14.sp,
             color: AppColors.primary,
             fontFamily: AppConstants.fontFamily,
           ),
           suffixIcon: suffixIcon,
           prefixIcon: prefixIcon,
           prefixIconConstraints: const BoxConstraints(
             minWidth: 40,
             minHeight: 0,
           ),
           border: OutlineInputBorder(
             borderRadius: .circular(14.r),
             borderSide: .none,
           ),
           focusedBorder: OutlineInputBorder(
             borderRadius: .circular(14.r),
             borderSide: .none,
           ),
         ),
         cursorColor: AppColors.primary,
         validator: validator,
         onTap: onTap,
         style: TextStyle(
           fontSize: 14.sp,
           color: AppColors.black,
           fontFamily: AppConstants.fontFamily,
         ),
         contextMenuBuilder: contextMenuBuilder,
       );
}
